#!/bin/sh /etc/rc.common
START=96
STOP=01
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/ucode -g 1000 /usr/libexec/unisoc-modem/traffic
    procd_set_param respawn 3600 5 0
    procd_set_param term_timeout 8
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    ubus -t 3 call unisoc.traffic flush >/dev/null 2>&1 || true
}
