#!/bin/sh /etc/rc.common
# Public IPv6 host routes for LAN clients (see /opt/mu300/bin/ndp-learn)
START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh /opt/mu300/bin/ndp-learn
	procd_set_param respawn 3600 10 0
	procd_close_instance
}
